version: "3"
services:
    web:
      build: ./services/apache-php
      container_name: web
      ports:
        - 8085:80
      links:
        - db
      volumes:
        - ./htdocs:/var/www/html

    db:
      build: ./services/mysql
      container_name: db
      ports:
          - 8090:3306
      environment:
        MYSQL_ROOT_PASSWORD: admin
      volumes:
        - db_data:/var/lib/mysql
        
    phpmyadmin:
      build: ./services/phpmyadmin
      container_name: myadmin
      links:
        - db:mysql_db_server
      ports:
        - 8086:80
      environment:
        MYSQL_ROOT_PASSWORD: admin 
        PMA_ARBITRARY: 1
volumes:
  db_data:
